postprocessor:
  name: gen
  APS_mode: True
  postprocessor_args:
    gamma: 0.1
    M: 100
  postprocessor_sweep:
    gamma_list: [0.01,0.1,0.5,1,2,5,10]
<<<<<<< HEAD
    M_list: [1, 2, 3, 4, 5, 6, 7, 50, 100, 200]
=======
    M_list: [10,50,100,200,500,1000]
>>>>>>> origin/main
