postprocessor:
  name: knn
  APS_mode: True
  postprocessor_args:
    K: 50
  postprocessor_sweep:
<<<<<<< HEAD
    K_list: [1, 2, 5, 10, 25, 50, 100, 200, 500, 750, 1000]
=======
    K_list: [50, 100, 200, 500, 1000]
>>>>>>> origin/main
