postprocessor:
  name: mds_ensemble
  APS_mode: True
  postprocessor_args:
    noise: 0.0014
<<<<<<< HEAD
    feature_type_list: [mean, mean, mean, mean, mean]      # flat/mean/stat
    #alpha_list: [1]
    reduce_dim_list: [none, none, none, none, none]  # none/capca/pca_50/lda
  postprocessor_sweep:
    noise_list: [0, 0.0025, 0.0014, 0.005, 0.01, 0.02, 0.04, 0.08]
  hyperparam_search_done: False
=======
    feature_type_list: [mean]     # flat/mean/stat
    alpha_list: [1]
    reduce_dim_list: [none]   # none/capca/pca_50/lda
  postprocessor_sweep:
    noise_list: [0.0014]
>>>>>>> origin/main
