postprocessor:
  name: rankfeat
  APS_mode: True
  postprocessor_args:
    accelerate: False
    temperature: 1
  postprocessor_sweep:
    accelerate_list: [False, True]
    temperature_list: [0.1, 1, 10, 100, 1000]
  hyperparam_search_done: False
